name: Run Tests 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pipenv
      - run: python3 -m venv venv
      - run: venv/Scripts/activate
      - run: pip install -r requirements.txt
      - run: python3 -m mypy .
      - run: python3 -m pytest
